export const BANKS_PAYU_LIST_REQUEST = 'BANKS_PAYU_LIST_REQUEST';
export const BANKS_PAYU_LIST_SUCCESS = 'BANKS_PAYU_LIST_SUCCESS';
export const BANKS_PAYU_LIST_FAIL = 'BANKS_PAYU_LIST_FAIL';

export const PSE_PAYU_SUBMIT_TRANSACTION_REQUEST = 'PSE_PAYU_SUBMIT_TRANSACTION_REQUEST';
export const PSE_PAYU_SUBMIT_TRANSACTION_SUCCESS = 'PSE_PAYU_SUBMIT_TRANSACTION_SUCCESS';
export const PSE_PAYU_SUBMIT_TRANSACTION_FAIL = 'PSE_PAYU_SUBMIT_TRANSACTION_FAIL';